### ISSUE TITLE
Privacy Settings: wiping metadata

### ISSUE THREAD

**Issue by Hong-King** [nicokaiser/hugo-theme-gallery#101]
Sometimes, people may just want to share photos without revealing the information of Exif, GPS or TIFF. 

Could you add an optional feature to show or wipe the metadata of photos that were published on blog?

**Comment by nicokaiser** [comment]
This is currently not possible with Hugo:

While you can disable metadata in the processed files (by changing the `includedFields` in [hugo.toml](https://github.com/nicokaiser/hugo-theme-gallery/blob/6db1464246e48aacc53dd5b156cf6034d088fb13/exampleSite/config/_default/hugo.toml#L43)) this will not prevent the original images to be published alongside the resized/compressed ones.

Since you might want to process images for the blog anyway, e.g. resize them to the maximum size you want viewers to be able to download (in most cases, just throwing in the high-resolution originals is a waste of storage space), the removal of metadata can be done in that step.
