### ISSUE TITLE
Viewing Resolution Adjust

### ISSUE THREAD

**Issue by Hansxsourse** [nicokaiser/hugo-theme-gallery#29]
Hi, thanks for the amazing work!
May I ask if there's any way to adjust the showing resolution for the images? And also if there's any way to control the compression quality. The displayed quality is much lower than the local one.

**Comment by nicokaiser** [comment]
You can copy the theme to your local installation (e.g. to `themes/gallery`) and just adjust the resolutions directly in the files:

 - `layouts/partial/album.html`: change the album thumbnail resolution `900x600` to your needs (keep in mind the aspect ratio has to be 3:2, otherwise you need to change the `aspect-[3/2]` class and re-compile the CSS)
 - `layouts/_default/page_gallery.html`: change the gallery thumbnail resolution `800x800` and the full image resolution `1600x1600`.

You can adjust the JPEG quality in your site configuration (hugo.toml): https://gohugo.io/content-management/image-processing/#processing-options

**Comment by TGNYC** [comment]
Hi! I adjusted the JPEG quality to 100 in my hugo.toml file; however, there is still a very noticeable resolution loss difference between the image in the gallery and the image when downloaded and viewed. Do you have any tips? @nicokaiser

**Comment by nicokaiser** [comment]
You might want to adjust the „fit 1600x1600“ value in gallery.html. This is the resolution your photos are displayed (you usually do not want to display photos in original resolution/quality because of file size).
