### ISSUE TITLE
Changing layout

### ISSUE THREAD

**Issue by shopgallery** [nicokaiser/hugo-theme-gallery#35]
I currently forked the project.
How can customize layout of gallery page so that it show 3 column in mobile view ?
thank.

**Comment by shopgallery** [comment]
Thank you so much for your answer, it worked for `page_albums.html` but actually I wanted to show 3 columns in `page_gallery.html`. So is there any way to do that ?

**Comment by shopgallery** [comment]
![Screenshot from 2024-01-19 23-09-33](https://github.com/nicokaiser/hugo-theme-gallery/assets/154798388/c793741a-c606-42f3-bfa4-a573990fca85)

**Comment by nicokaiser** [comment]
I understand. This is entirely rendered by the [flickr-justified-gallery](https://github.com/nk-o/flickr-justified-gallery/) module, so you might want to look there and add options to main.js accordingly. I'm not sure if this can be adjusted to display multiple rows at such small screens, since the row heights are (pretty much) fixed.

**Comment by shopgallery** [comment]
OK, thank you so much, I'll try.
And thank you for your work, it's a great template.
