### ISSUE TITLE
Image remains horizontal despite orientation tags in TIFF

### ISSUE THREAD

**Issue by CallMeL** [nicokaiser/hugo-theme-gallery#50]
Hi Nico, thank you for this brilliant work. 

 I was trying to add photos I took using a camera, but all the photos stay horizontal despite the orientation tags in TIFF is 6, do I need to write it specifically in Exif tag?  Is there any chance to read the information in TIFF tag?
<img width="320" alt="Screenshot 2024-03-14 at 20 36 09" src="https://github.com/nicokaiser/hugo-theme-gallery/assets/55145817/163df9df-fb68-4458-8f6e-b28e199e3936">

Edited: in the general tag the orientation is also 6, I didn't find the orientation row in Exif tag

Thanks again!

**Comment by nicokaiser** [comment]
Thanks @CallMeL, glad you like the theme!
I'm not sure if Hugo can process TIFF tags at all, could you send me an example photo where this occurs?

**Comment by CallMeL** [comment]
Hi @nicokaiser , [this](https://github.com/CallMeL/gallery/blob/main/content/Travel/Salzburg/DSCF0999.JPG) is one example image

**Comment by nicokaiser** [comment]
Thanks for the example! After short investigation I found out that the Orientation tag is not read at all in the example, because it was missing in the `includeFields`.

Could you change your `hugo.toml` and add the `Orientation` entry to `includeFields`?

```diff
  [imaging]
    quality = 75
    resampleFilter = "CatmullRom"
    [imaging.exif]
      disableDate = false
      disableLatLong = true
+     includeFields = "ImageDescription|Orientation"
```

This way the Orientation field is read from the images and used for rotation.

There is another way to achieve this without needing to include this field, but that would require at least Hugo v0.121.2. I may use this more elegant way in a future version (#51).

**Comment by CallMeL** [comment]
Thank you for the quick reply, it solved my problem perfectly!
