### ISSUE TITLE
Description on image view

### ISSUE THREAD

**Issue by retiolus** [nicokaiser/hugo-theme-gallery#59]
Hi! I'm using and loving this theme, but would like to know if it is possible to show image description/title when it is opened and the bottom of the image in single view like here, if not, could this be implemented?

![image](https://github.com/nicokaiser/hugo-theme-gallery/assets/65604466/8a4742cf-96d7-43ed-8a32-b077422697a8)

**Comment by nicokaiser** [comment]
Oh, this seems to be broken in the example, I’m looking into it how to fix it.

**Comment by nicokaiser** [comment]
This is fixed in version 4.1.6, could you try to update?
Captions can now be set either by using the EXIF data of the images, or the resource metadata in the frontmatter, as described in the [Metadata section in README.md](https://github.com/nicokaiser/hugo-theme-gallery?tab=readme-ov-file#metadata).
