### ISSUE TITLE
Using with Blowfish ?

### ISSUE THREAD

**Issue by Phil89a** [nicokaiser/hugo-theme-gallery#60]
Can anyone point me how to use this wonderful theme with Blowfish?

I am in the process of trying to move from WordPress and have settled on Blowfish as my base theme.  Being a photography portfolio site, I also want to use Photoswipe for displaying my images; so all help and pointers appreciated 

Thanks

**Comment by nicokaiser** [comment]
I'm sorry, I cannot provide an integration with other themes. This theme is not really modular, since its goal is to stay very simple.
You could however ditch into the JavaScript in `lightbox.js` and try to adapt it for other themes like Blowfish, but since it is very much tailored to this theme, this would require quite some HTML/CSS/JS knowledge.
