### ISSUE TITLE
feature req: Dynamic caption plugin for PhotoSwipe

### ISSUE THREAD

**Issue by BartVanEynde** [nicokaiser/hugo-theme-gallery#63]
Hi,
I see there are some preparations done for this dynamic caption plugin.

would it be possible to add the resources > title, 
maybe also a longer, multiline description? into this dynamic caption plugin?

many thanks

**Comment by nicokaiser** [comment]
Thanks for your feature request and the idea!
I don't know if the Dynamic Caption Plugin has any length restriction, so captions can in theory be very long.

The plugin seems to support HTML tags in the caption, so inserting "<br>" can add line breaks. However this might not be a good idea in the EXIF tags, since EXIF should not be HTML at all. However maybe it can be used in the resource/title fields in the markdown frontmatter files.
