### ISSUE TITLE
adding videoclips

### ISSUE THREAD

**Issue by 22decembre** [nicokaiser/hugo-theme-gallery#85]
Can we have videoclips ? Not only pictures ?

Thank you for your theme. It's great.

**Comment by nicokaiser** [comment]
Thanks for the kind words!
Adding video support is currently a bit out of scope, since Hugo does not have video processing capabilities, and cannot read video metadata (I guess). 
So adding video support would require a whole different technology with quite complex processing. 

Furthermore, adding images to a SSG-generates is already challenging since multiple copies need to be stored and copied around. With videos (in all different formats required) this would completely exceed the complexity that can be handled.

I had some success adding (static! Already correctly converted for web!) videos to the static `public` directory and adding them to the album pages (however of course not as part of the gallery), but this is really out of scope of this simple theme.

**Comment by 22decembre** [comment]
I was thinking here about videos without processing them.

I am thought really ignorant of the challenges and complexities of that.

Thanks for explaining.
