### ISSUE TITLE
Custom resources ordering is ignored, `Name` is used instead

### ISSUE THREAD

**Issue by coaxial** [nicokaiser/hugo-theme-gallery#97]
This relates to that line: https://github.com/nicokaiser/hugo-theme-gallery/blob/6bbd8be6595b23f3fc9780a38ec31a0c2e86386a/layouts/partials/gallery.html#L26

Consider this:

```markdown
# index.md
---
title: My Album
resources:
  - src: image-2.jpg
  - src: image-1.jpg
```

I would expect the album to show `image-2.jpg` and then `image-1.jpg`. But with the current implementation, it will re-order my custom list and put it back in `Name` order and so I get `image-1.jpg` and then `image-2.jpg`.

I suspect it would make more sense to respect the custom resources ordering because if the user went through the effort of manually reordering, then it most likely means they'd like the images to be in that custom order.

What do you think @nicokaiser?

**Comment by nicokaiser** [comment]
I don't think this is even possible: even when just using `{{ range $images }}` (with no sort order defined), the images are returned ordered by name (default). The `resources` front matter is only useful to change or add additional metadata to existing resources: `.Resources.ByType "image"` will return "*.jpg", even one might assume that in your example only two images (`image-1.jpg` and `image-2.jpg`) are returned.

I have seen something like `- src: **.jpeg` in other themes like [this one](https://github.com/nmasse-itix/photo-stream/blob/ee603a4cf4d121e91e122e916434364d69918b8d/exampleSite/content/animals/index.md?plain=1#L9). This like does nothing, since all images are used anyway.

Or am I missing something?

**Comment by nicokaiser** [comment]
Additional reading: https://discourse.gohugo.io/t/can-page-resources-be-put-into-a-custom-order/13100/8

There might be an option to custom order page resources: we could pass through the "Params", so they can be used in `sort_by`:

```md
---
date: 2023-04-01
title: Cats
sort_by: Params.weight
categories: ["animals", "nature"]
params:
  featured_image: manja-vitolic-gKXKBY-C-Dk-unsplash.jpg
resources:
  - src: alexander-london-mJaD10XeD7w-unsplash.jpg
    title: Brown tabby cat on white stairs by Alexander London
    params:
      weight: 20
  - src: amber-kipp-75715CVEJhI-unsplash.jpg
    title: Selective focus photography of orange and white cat on brown table by Amber Kipp
    params:
      weight: 10
  - src: manja-vitolic-gKXKBY-C-Dk-unsplash.jpg
    title: "Gipsy the Cat was sitting on a bookshelf one afternoon and just stared right at me, kinda saying: “Will you take a picture already?”"
    params:
      cover: true
      weight: 30
```

However this would require to set `params.weight` for every image. Better than nothing...

**Comment by nicokaiser** [comment]
Could you try upgrading the theme to version 4.6.0? This version allows the `weight` param to be used in front matter, like in the above example.
Using the resource order from front matter does not seem to be possible with Hugo (correct me if I'm wrong)...
