### ISSUE TITLE
Anything but static images are ignored

### ISSUE THREAD

**Issue by coaxial** [nicokaiser/hugo-theme-gallery#98]
This line: https://github.com/nicokaiser/hugo-theme-gallery/blob/6bbd8be6595b23f3fc9780a38ec31a0c2e86386a/layouts/partials/gallery.html#L4

Makes the theme ignore anything but pictures, which makes sense. Except that GIF or webp (or the iPhone's "live" pictures) are also pictures (conceptually), but they're ignored and don't show in the gallery.

I personally think it would be cool to have all these types mixed together in an album and be closer to the common interpretation of what an album is.

Would it make sense to extend the notion of what is a picture to include moving images and even videos (as #85 is proposing)?

**Comment by nicokaiser** [comment]
- WebP images seem to work, at least static images. They will be converted to JPEG though (because everything is converted to the right size, preview images, etc.)
- Animated WebP images will crash Hugo, I think Hugo's image library does not support them, so no luck here.
- Animated GIFs work … kind of: they are displayed as static (since they wil also be converted to JPEG).

I think adding videos would make this much much more complex, so I deliberately did not consider this at all. Adding video support would require generating thumbnails of videos (Hugo might support this, I don't know); but also modifying PhotosSwipe to add a video player. IMO this exceeds the scope of this theme quite a bit ;-)
