### ISSUE TITLE
Animated GIFs are displayed as static images

### ISSUE THREAD

**Issue by Soblow** [nicokaiser/hugo-theme-gallery#99]
Hello! First, thanks for the project, I use it since a few months and it works flawlessly.

I've noticed that animated GIFs are transformed into a lower-resolution static image of the first frame when shown in the gallery...

From what I know, this is due to https://github.com/nicokaiser/hugo-theme-gallery/blob/6db1464246e48aacc53dd5b156cf6034d088fb13/layouts/partials/gallery.html#L34 , because the image module of Hugo doesn't handle GIFs pretty well...

Would it be possible to have some kind of exception for GIFs so that they can skip the transform process?

Thank you!

**Comment by nicokaiser** [comment]
Yes, this is kind of the same as #98: images are processed (yes, all of them, in order to ensure a compatible format and good compression).
You could maybe try to exclude GIFs from this transformation and deliver them directly, but this is clearly out of scope of this theme, since animated/video content is a whole different story than photos.

**Comment by Soblow** [comment]
Oh, alright, I'll try to write a quick patch and send it here if other people are interested in it.
Thanks for your quick response!

**Comment by woefi** [comment]
I experimented with a patched „gallery.html“ which excludes gifs and svgs from „processing“ and it kind of worked(-ish). (and I‘m not sue the gifs were still animating…)
But my programming abilities are very „trial-and-error-until-something-sticks“ so I‘m rather embarrased showing my code…
